src/Entity/Rent.php
<?php

namespace App\Entity;

use App\Repository\RentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=RentRepository::class)
 */
class Rent
{
    public const RENT_NORMAL = "Normale";
    public const RENT_ONLINE = "En ligne";
    public const DEPOSIT_PAY_CHEQUE = "Chèque bancaire";
    public const DEPOSIT_ONLINE = "En ligne";
    public const DEPOSIT_OWNER = "Propriétaire";

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Owner::class, inversedBy="rents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Owner;

    /**
     * @ORM\ManyToOne(targetEntity=Apartment::class, inversedBy="rents")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank(message="Sélectionnez un choix")
     */
    private $Apartment;

    /**
     * @ORM\Column(type="datetime")
     */
    private $startingDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $endingDate;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $rentType;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2)
     * @Assert\NotBlank(message="Sélectionnez un choix")
     */
    private $total;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isPaid;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $settlementDate;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $deposit;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="Sélectionnez un choix")
     */
    private $comment;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=RentRow::class, mappedBy="rent")
     */
    private $rentRows;

    public function __construct()
    {
        $this->rentRows = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOwner(): ?Owner
    {
        return $this->Owner;
    }

    public function setOwner(?Owner $Owner): self
    {
        $this->Owner = $Owner;

        return $this;
    }

    public function getApartment(): ?Apartment
    {
        return $this->Apartment;
    }

    public function setApartment(?Apartment $Apartment): self
    {
        $this->Apartment = $Apartment;

        return $this;
    }

    public function getStartingDate(): ?\DateTimeInterface
    {
        return $this->startingDate;
    }

    public function setStartingDate(\DateTimeInterface $startingDate): self
    {
        $this->startingDate = $startingDate;

        return $this;
    }

    public function getEndingDate(): ?\DateTimeInterface
    {
        return $this->endingDate;
    }

    public function setEndingDate(\DateTimeInterface $endingDate): self
    {
        $this->endingDate = $endingDate;

        return $this;
    }

    public function getRentType(): ?string
    {
        return $this->rentType;
    }

    public function setRentType(string $rentType): self
    {
        $this->rentType = $rentType;

        return $this;
    }

    public function getTotal(): ?string
    {
        return $this->total;
    }

    public function setTotal(string $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getIsPaid(): ?bool
    {
        return $this->isPaid;
    }

    public function setIsPaid(bool $isPaid): self
    {
        $this->isPaid = $isPaid;

        return $this;
    }

    public function getSettlementDate(): ?\DateTimeInterface
    {
        return $this->settlementDate;
    }

    public function setSettlementDate(?\DateTimeInterface $settlementDate): self
    {
        $this->settlementDate = $settlementDate;

        return $this;
    }

    public function getDeposit(): ?string
    {
        return $this->deposit;
    }

    public function setDeposit(string $deposit): self
    {
        $this->deposit = $deposit;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|RentRow[]
     */
    public function getRentRows(): Collection
    {
        return $this->rentRows;
    }

    public function addRentRow(RentRow $rentRow): self
    {
        if (!$this->rentRows->contains($rentRow)) {
            $this->rentRows[] = $rentRow;
            $rentRow->setRent($this);
        }

        return $this;
    }

    public function removeRentRow(RentRow $rentRow): self
    {
        if ($this->rentRows->removeElement($rentRow)) {
            // set the owning side to null (unless already changed)
            if ($rentRow->getRent() === $this) {
                $rentRow->setRent(null);
            }
        }

        return $this;
    }
}

src/Controller/Rent/RentConfirmationController.php
<?php

namespace App\Controller\Rent;

use DateTime;
use App\Entity\Rent;
use App\Entity\RentRow;
use App\Cart\CartService;
use App\Form\CartConfirmationType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class RentConfirmationController extends AbstractController
{
    protected $cartService;
    protected $em;

    public function __construct(CartService $cartService, EntityManagerInterface $em)
    {
        $this->cartService = $cartService;
        $this->em = $em;
    }

    /**
     * @Route("/rent/confirm", name="rent_confirm")
     * @IsGranted("ROLE_ADMIN", message="Vous devez être connecté pour créer une facture")
     */
    public function confirm(Request $request)
    {
        // Lecture des données du formulaire
        $form = $this->createForm(CartConfirmationType::class);

        $form->handleRequest($request);

        // Si le formulaire n'est pas soumis : dégager
        if (!$form->isSubmitted()) {
            // Message Flash et redirection
            $this->addFlash('warning', 'Vous devez remplir le formulaire');

            return $this->redirectToRoute('cart_show');
        }

        // Si l'utilisateur n'est pas authentifié : dégager
        $user = $this->getUser();

        // Si le panier et vide : dégager
        $cartItems = $this->cartService->getDetailedCartItems();

        if(count($cartItems) === 0) {
            // Message Flash et redirection
            $this->addFlash('warning', 'Vous ne pouvez pas valider un panier vide');

            return $this->redirectToRoute('cart_show');
        }

        /** @var Rent */
        $rent = $form->getData();

        $rent->setCreatedAt(new DateTime())
            ->setIsPaid(false)
            ->setOwner($rent->getApartment()->getOwner());
        $this->em->persist($rent);

        $total = 0;
        foreach($this->cartService->getDetailedCartItems() as $cartItem) {
            $rentRow = new RentRow;
            $rentRow->setRent($rent)
                ->setService($cartItem->service)
                ->setServiceLabel($cartItem->service->getLabel())
                ->setQuantity($cartItem->qty)
                ->setPrice($cartItem->service->getPrice())
                ->setTotalRow($cartItem->getTotal());

            $this->em->persist($rentRow);

            $total += $cartItem->getTotal();
        }

        $rent->setTotal($total);

        $this->em->flush();

        $this->cartService->empty();

        $this->addFlash('success', 'La facture a bien été enregistrée');
        return $this->redirectToRoute('rent_list');

    }
}

src/Controller/Rent/RentListController.php
<?php

namespace App\Controller\Rent;

use Twig\Environment;
use App\Repository\RentRepository;
use App\Repository\RentRowRepository;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class RentListController extends AbstractController
{

    protected $rentRepository;
    protected $rentRowRepository;
    protected $urlGenerator;

    public function __construct(RentRepository $rentRepository, RentRowRepository $rentRowRepository, UrlGeneratorInterface $urlGenerator)
    {
        $this->rentRepository = $rentRepository;
        $this->rentRowRepository = $rentRowRepository;
        $this->urlGenerator = $urlGenerator;
    }

    /** 
     * @Route("/rent", name="rent_list")
     * @IsGranted("ROLE_USER", message="Vous devez être connecté pour à la liste des locations")
     */
    public function index()
    {

        /** @var User */
        $user = $this->getUser();

        $rentRows = $this->rentRepository->findBy([], ['createdAt' => 'DESC']);

        return $this->render('rent/index.html.twig', [
            'rents' => $rentRows,
            'urlGenerator' => $this->urlGenerator
        ]);
    }

    /**
     * @Route("/rent/{id}", name="rent_show", requirements={"id":"\d+"})
     * @IsGranted("ROLE_USER", message="Vous devez être connecté pour accder à cette page")
     */
    public function show(int $id)
    {
        $rentItems = $this->rentRowRepository->findBy(["rent" => $id]);

        $total = 0;

        foreach($rentItems as $item) {
            $total += $item->getPrice() * $item->getQuantity();
        }

        return $this->render('rent/show.html.twig', [
            'items' => $rentItems,
            'total' => $total,
            'urlGenerator' => $this->urlGenerator
        ]);
    }
}

templates/rent/index.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Liste des facturations
{% endblock %}

{% block body %}
	<h1 class="mb-5">Liste des facturations</h1>

	<table class="table table-striped">
		<thead>
			<tr class="text-center">
				<th>Date de création</th>
				<th>Location N°</th>
				<th>Appartement</th>
				<th>Propriétaire</th>
				<th>Arrivée</th>
				<th>Départ</th>
				<th>Total</th>
				<th>Statut</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{% for r in rents %}
				<tr class="text-center">
					<td>{{ r.createdAt|date('d/m/Y') }}</td>
					<td>{{ r.id }}</td>
					<td>{{ r.apartment.id }}</td>
					<td>{{ r.owner.firstName }}
						{{ r.owner.lastName }}</td>
					<td>{{ r.startingDate|date('d/m/Y') }}</td>
					<td>{{ r.endingDate|date('d/m/Y') }}</td>
					<td>{{ r.total }}</td>
					{% if r.isPaid == true %}
						<td class="text-success">Réglée</td>
					{% else %}
						<td class="text-warning">En cours</td>
					{% endif %}
					<td>
						<a class="text-decoration-none" href="{{urlGenerator.generate('rent_show', {'id': r.id})}}">Détails
							<i class="fa-solid fa-pen-to-square"></i>
						</a>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/rent/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Détails de la facture n°{{ items[0].rent.id }}
{% endblock %}

{% block body %}
	<h1 class="mb-5">Détails de la facture n°{{ items[0].rent.id }}</h1>
	<div class="row mb-4 mx-0">
		<div class="card text-dark col-6 col-md-4 mb-3 col-4 px-0">
			<div class="card-header fw-bold">
				<em>Propriétaire</em>
			</div>
			<div class="card-body">
				<p class="card-text">{{ items[0].rent.owner.firstName }}
					{{ items[0].rent.owner.lastName }}</p>
			</div>
		</div>
		<div class="card text-dark col-6 col-md-4 mb-3 col-4 px-0">
			<div class="card-header fw-bold">
				<em>Appartment</em>
			</div>
			<div class="card-body">
				<p class="card-text">{{ items[0].rent.apartment.id }}</p>
			</div>
		</div>
		<div class="card text-dark col-6 col-md-4 mb-3 col-4 px-0">
			<div class="card-header fw-bold">
				<em>Type de location</em>
			</div>
			<div class="card-body">
				<p class="card-text">{{ items[0].rent.rentType }}</p>
			</div>
		</div>
		<div class="card text-dark col-6 col-md-4 mb-3 col-4 px-0">
			<div class="card-header fw-bold">
				<em>Date d'entrée</em> | <em>Date de sortie</em>
			</div>
			<div class="card-body">
				<p class="card-text">{{ items[0].rent.startingDate| date('d/m/Y') }}
					|
					{{ items[0].rent.endingDate| date('d/m/Y') }}</p>
			</div>
		</div>
		<div class="card text-dark col-6 col-md-4 mb-3 col-4 px-0">
			<div class="card-header fw-bold">
				<em>Caution</em>
			</div>
			<div class="card-body">
				<p class="card-text">{{ items[0].rent.deposit }}
				</p>
			</div>
		</div>
		<div class="card text-dark col-6 col-md-4 mb-3 col-4 px-0">
			<div class="card-header fw-bold">
				<em>Statut Règlement</em>
			</div>
			<div class="card-body">
				{% if items[0].rent.isPaid == true %}
					<p class="card-text">Réglée le
						{{ items[0].rent.SettlementDate| date('d/m/Y') }}
					</p>
				{% else %}
					<p class="card-text">En attente
					</p>

				{% endif %}
			</div>
		</div>
	</div>

	<table class="table table-striped">
		<thead>
			<tr>
				<th scope="col" class="text-center">ID Service</th>
				<th scope="col">Service</th>
				<th scope="col">Prix (€)</th>
				<th scope="col" class="text-center">Quantité</th>
				<th scope="col">Total ligne (€ TTC)</th>
			</tr>
		</thead>
		<tbody>
			{% for item in items %}
				<tr>
					<td class="text-center">{{ item.service.id }}</td>
					<td>{{ item.serviceLabel }}</td>
					<td>{{ item.price }}</td>
					<td class="text-center">{{ item.quantity }}</td>
					<td>{{ item.totalRow }}</td>
				</tr>
			{% endfor %}
		</tbody>
		<tfoot>
			<tr class="fs-6">
				<td colspan="4">Total :</td>
				<td>{{ total|format_number({fraction_digit: 2}, style='decimal') }}</td>
			</tr>
		</tfoot>
	</table>
	<a href="{{ path('rent_list') }}" class="btn btn-outline-primary">Retour</a>
{% endblock %}